
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.14.0
 * Query Engine version: 717184b7b35ea05dfa71a3236b7af656013e1e49
 */
Prisma.prismaVersion = {
  client: "6.14.0",
  engine: "717184b7b35ea05dfa71a3236b7af656013e1e49"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AddressScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  address1: 'address1',
  address2: 'address2',
  city: 'city',
  region: 'region',
  postalCode: 'postalCode',
  addressType: 'addressType',
  isPrimary: 'isPrimary',
  countryId: 'countryId',
  userId: 'userId',
  organizationId: 'organizationId'
};

exports.Prisma.ApiTokenScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  tokenHash: 'tokenHash',
  name: 'name',
  expiresAt: 'expiresAt',
  lastUsedAt: 'lastUsedAt',
  revoked: 'revoked'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  entityId: 'entityId',
  entityType: 'entityType',
  action: 'action',
  userId: 'userId',
  organizationId: 'organizationId',
  changes: 'changes'
};

exports.Prisma.CountryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  alpha2: 'alpha2',
  alpha3: 'alpha3',
  countryCode: 'countryCode',
  iso3166_2: 'iso3166_2',
  region: 'region',
  subRegion: 'subRegion',
  intermediateRegion: 'intermediateRegion',
  regionCode: 'regionCode',
  subRegionCode: 'subRegionCode',
  intermediateRegionCode: 'intermediateRegionCode'
};

exports.Prisma.EmailScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  email: 'email',
  public: 'public',
  primary: 'primary',
  verified: 'verified',
  verifyToken: 'verifyToken',
  verifyExpires: 'verifyExpires',
  userId: 'userId',
  emailType: 'emailType',
  organizationId: 'organizationId'
};

exports.Prisma.InviteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt',
  email: 'email',
  token: 'token',
  inviterId: 'inviterId',
  organizationId: 'organizationId',
  status: 'status',
  roleId: 'roleId'
};

exports.Prisma.LinkScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  url: 'url',
  userId: 'userId',
  organizationId: 'organizationId'
};

exports.Prisma.LoginAttemptScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  email: 'email',
  success: 'success',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  location: 'location',
  reason: 'reason'
};

exports.Prisma.OAuthAccountScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  provider: 'provider',
  providerUserId: 'providerUserId',
  userId: 'userId'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name'
};

exports.Prisma.OrganizationMemberScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  roleId: 'roleId',
  userId: 'userId',
  organizationId: 'organizationId'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  action: 'action',
  subject: 'subject',
  description: 'description'
};

exports.Prisma.PhoneNumberScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  phone: 'phone',
  phoneType: 'phoneType',
  userId: 'userId',
  primary: 'primary',
  organizationId: 'organizationId'
};

exports.Prisma.PlanScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  price: 'price',
  interval: 'interval',
  features: 'features',
  active: 'active'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  organizationId: 'organizationId'
};

exports.Prisma.SecurityEventScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  eventType: 'eventType',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  metadata: 'metadata'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  organizationId: 'organizationId',
  planId: 'planId',
  stripeCustomerId: 'stripeCustomerId',
  stripeSubscriptionId: 'stripeSubscriptionId',
  stripePriceId: 'stripePriceId',
  stripeCurrentPeriodEnd: 'stripeCurrentPeriodEnd',
  status: 'status'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  description: 'description',
  organizationId: 'organizationId'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  teamId: 'teamId',
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.StoredFileScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  provider: 'provider',
  providerFileId: 'providerFileId',
  folder: 'folder',
  filename: 'filename',
  originalName: 'originalName',
  mimeType: 'mimeType',
  size: 'size',
  url: 'url',
  publicUrl: 'publicUrl',
  width: 'width',
  height: 'height',
  metadata: 'metadata',
  userId: 'userId',
  organizationId: 'organizationId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  firstName: 'firstName',
  lastName: 'lastName',
  isSuperAdmin: 'isSuperAdmin',
  bio: 'bio',
  displayName: 'displayName',
  password: 'password',
  passwordResetToken: 'passwordResetToken',
  passwordResetExpires: 'passwordResetExpires',
  emailValidated: 'emailValidated',
  validateEmailToken: 'validateEmailToken',
  validateEmailTokenExpires: 'validateEmailTokenExpires',
  activeOrganizationId: 'activeOrganizationId',
  twoFactorEnabled: 'twoFactorEnabled',
  twoFactorSecret: 'twoFactorSecret',
  twoFactorRecoveryCodes: 'twoFactorRecoveryCodes',
  twoFactorMethod: 'twoFactorMethod',
  lastSuccessfulLogin: 'lastSuccessfulLogin',
  lastFailedLogin: 'lastFailedLogin',
  failedLoginCount: 'failedLoginCount',
  lockedUntil: 'lockedUntil',
  isActive: 'isActive',
  deactivatedAt: 'deactivatedAt',
  termsAcceptedAt: 'termsAcceptedAt',
  privacyPolicyAcceptedAt: 'privacyPolicyAcceptedAt'
};

exports.Prisma.UserPreferenceScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  key: 'key',
  value: 'value'
};

exports.Prisma.UserSessionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastActiveAt: 'lastActiveAt',
  userId: 'userId',
  deviceInfo: 'deviceInfo',
  ipAddress: 'ipAddress',
  isValid: 'isValid',
  twoFactorVerified: 'twoFactorVerified'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.AddressType = exports.$Enums.AddressType = {
  HOME: 'HOME',
  WORK: 'WORK',
  VENUE: 'VENUE',
  EVENT: 'EVENT',
  OTHER: 'OTHER'
};

exports.EmailType = exports.$Enums.EmailType = {
  PERSONAL: 'PERSONAL',
  WORK: 'WORK',
  OTHER: 'OTHER'
};

exports.InviteStatus = exports.$Enums.InviteStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  EXPIRED: 'EXPIRED'
};

exports.FailureReason = exports.$Enums.FailureReason = {
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  INVALID_2FA: 'INVALID_2FA',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS'
};

exports.PhoneType = exports.$Enums.PhoneType = {
  HOME: 'HOME',
  WORK: 'WORK',
  MOBILE: 'MOBILE',
  OTHER: 'OTHER'
};

exports.SecurityEventType = exports.$Enums.SecurityEventType = {
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',
  TWO_FACTOR_ENABLED: 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED: 'TWO_FACTOR_DISABLED',
  RECOVERY_CODES_GENERATED: 'RECOVERY_CODES_GENERATED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  SUSPICIOUS_LOGIN_ATTEMPT: 'SUSPICIOUS_LOGIN_ATTEMPT',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  LOGIN_LOCATION_CHANGE: 'LOGIN_LOCATION_CHANGE',
  API_TOKEN_CREATED: 'API_TOKEN_CREATED',
  API_TOKEN_REVOKED: 'API_TOKEN_REVOKED',
  API_TOKEN_ROTATED: 'API_TOKEN_ROTATED'
};

exports.SubscriptionStatus = exports.$Enums.SubscriptionStatus = {
  ACTIVE: 'ACTIVE',
  CANCELED: 'CANCELED',
  PAST_DUE: 'PAST_DUE',
  INCOMPLETE: 'INCOMPLETE',
  INCOMPLETE_EXPIRED: 'INCOMPLETE_EXPIRED',
  TRIALING: 'TRIALING'
};

exports.StorageProvider = exports.$Enums.StorageProvider = {
  LOCAL: 'LOCAL',
  S3: 'S3',
  CLOUDINARY: 'CLOUDINARY',
  IMAGEKIT: 'IMAGEKIT',
  GCS: 'GCS'
};

exports.TwoFactorMethod = exports.$Enums.TwoFactorMethod = {
  NONE: 'NONE',
  AUTHENTICATOR: 'AUTHENTICATOR',
  SMS: 'SMS',
  EMAIL: 'EMAIL'
};

exports.Prisma.ModelName = {
  Address: 'Address',
  ApiToken: 'ApiToken',
  AuditLog: 'AuditLog',
  Country: 'Country',
  Email: 'Email',
  Invite: 'Invite',
  Link: 'Link',
  LoginAttempt: 'LoginAttempt',
  OAuthAccount: 'OAuthAccount',
  Organization: 'Organization',
  OrganizationMember: 'OrganizationMember',
  Permission: 'Permission',
  PhoneNumber: 'PhoneNumber',
  Plan: 'Plan',
  Role: 'Role',
  SecurityEvent: 'SecurityEvent',
  Subscription: 'Subscription',
  Team: 'Team',
  TeamMember: 'TeamMember',
  StoredFile: 'StoredFile',
  User: 'User',
  UserPreference: 'UserPreference',
  UserSession: 'UserSession'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
