
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.11.0
 * Query Engine version: 9c30299f5a0ea26a96790e13f796dc6094db3173
 */
Prisma.prismaVersion = {
  client: "6.11.0",
  engine: "9c30299f5a0ea26a96790e13f796dc6094db3173"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastSeen: 'lastSeen',
  onlineStatus: 'onlineStatus',
  status: 'status',
  developer: 'developer',
  role: 'role',
  email: 'email',
  emailConfirmed: 'emailConfirmed',
  username: 'username',
  firstName: 'firstName',
  lastName: 'lastName',
  password: 'password',
  passwordResetToken: 'passwordResetToken',
  passwordResetExpires: 'passwordResetExpires',
  confirmEmailToken: 'confirmEmailToken',
  confirmEmailExpires: 'confirmEmailExpires',
  applicationDate: 'applicationDate',
  inactiveDate: 'inactiveDate',
  inquiryDate: 'inquiryDate',
  membershipDate: 'membershipDate',
  renewalDate: 'renewalDate',
  terminationDate: 'terminationDate',
  terminationNotes: 'terminationNotes',
  terminationRequestedBy: 'terminationRequestedBy',
  transferDate: 'transferDate',
  location: 'location',
  phone: 'phone',
  bio: 'bio',
  facebook: 'facebook',
  twitter: 'twitter',
  youtube: 'youtube',
  linkedin: 'linkedin',
  instagram: 'instagram',
  website: 'website',
  industry: 'industry',
  timeInIndustry: 'timeInIndustry',
  ssoUrl: 'ssoUrl',
  address: 'address',
  address2: 'address2',
  cell: 'cell',
  chapterTitle: 'chapterTitle',
  city: 'city',
  comments: 'comments',
  company: 'company',
  fax: 'fax',
  hear: 'hear',
  hearOther: 'hearOther',
  internalComments: 'internalComments',
  launchComplete: 'launchComplete',
  mentorName: 'mentorName',
  merchantCircle: 'merchantCircle',
  multipleBusinesses: 'multipleBusinesses',
  multipleLocations: 'multipleLocations',
  numberOfEmployees: 'numberOfEmployees',
  organizer: 'organizer',
  otherBusinesses: 'otherBusinesses',
  otherLocations: 'otherLocations',
  postcode: 'postcode',
  promoter: 'promoter',
  recognized: 'recognized',
  salesAgentName: 'salesAgentName',
  state: 'state',
  strategizer: 'strategizer',
  substitute: 'substitute',
  tagline: 'tagline',
  terminatedByName: 'terminatedByName',
  terminationComments: 'terminationComments',
  terminationReason: 'terminationReason',
  thinker: 'thinker',
  title: 'title',
  type: 'type',
  vet: 'vet',
  activeDuty: 'activeDuty',
  militaryBranch: 'militaryBranch',
  notifyByEmail: 'notifyByEmail',
  notifyBySMS: 'notifyBySMS',
  notifyByWeb: 'notifyByWeb',
  notifyByMobile: 'notifyByMobile'
};

exports.Prisma.ChapterScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  establishedDate: 'establishedDate',
  name: 'name',
  description: 'description',
  address: 'address',
  address2: 'address2',
  city: 'city',
  state: 'state',
  postCode: 'postCode',
  latitude: 'latitude',
  longitude: 'longitude',
  facebook: 'facebook',
  virtual: 'virtual',
  meetingUrl: 'meetingUrl',
  meetingDay: 'meetingDay',
  meetingTime: 'meetingTime',
  meetingDetails: 'meetingDetails',
  status: 'status',
  substituteGroupId: 'substituteGroupId',
  regionId: 'regionId'
};

exports.Prisma.MeetingScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  date: 'date',
  chapterId: 'chapterId',
  isVisitorDay: 'isVisitorDay'
};

exports.Prisma.MeetingPresenceScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  attendance: 'attendance',
  other: 'other',
  meetingId: 'meetingId',
  memberId: 'memberId'
};

exports.Prisma.SubstituteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  meetingDate: 'meetingDate',
  sentById: 'sentById',
  substituteId: 'substituteId'
};

exports.Prisma.AttendanceReminderScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  chapterId: 'chapterId',
  sentById: 'sentById',
  sentToId: 'sentToId'
};

exports.Prisma.AwardTypeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  description: 'description'
};

exports.Prisma.AwardScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  awardedDate: 'awardedDate',
  userId: 'userId',
  awardTypeId: 'awardTypeId'
};

exports.Prisma.ChapterMemberScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  chapterId: 'chapterId',
  memberId: 'memberId'
};

exports.Prisma.UploadScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  format: 'format',
  originalFilename: 'originalFilename',
  publicId: 'publicId',
  resourceType: 'resourceType',
  secureUrl: 'secureUrl',
  signature: 'signature',
  thumbnailUrl: 'thumbnailUrl',
  url: 'url',
  type: 'type',
  userId: 'userId',
  userBgId: 'userBgId',
  chapterId: 'chapterId'
};

exports.Prisma.SubstituteGroupScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name'
};

exports.Prisma.TerritoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name'
};

exports.Prisma.RegionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  territoryId: 'territoryId'
};

exports.Prisma.IndustryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name'
};

exports.Prisma.ReferralScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  referralDate: 'referralDate',
  rating: 'rating',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  notes: 'notes',
  fromIndustry: 'fromIndustry',
  toIndustry: 'toIndustry',
  sentById: 'sentById',
  fromId: 'fromId',
  toId: 'toId',
  fromChapterId: 'fromChapterId',
  toChapterId: 'toChapterId'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  read: 'read',
  type: 'type',
  message: 'message',
  referenceId: 'referenceId',
  referenceType: 'referenceType',
  actorId: 'actorId',
  toId: 'toId'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  date: 'date',
  amount: 'amount',
  enteredBy: 'enteredBy',
  enteredOn: 'enteredOn',
  industry: 'industry',
  state: 'state',
  chapterId: 'chapterId',
  userId: 'userId',
  referralId: 'referralId'
};

exports.Prisma.TestimonialScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  text: 'text',
  fromId: 'fromId',
  toId: 'toId'
};

exports.Prisma.PowerHourScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  date: 'date',
  time: 'time',
  details: 'details',
  status: 'status',
  fromId: 'fromId',
  toId: 'toId'
};

exports.Prisma.BlogCategoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  slug: 'slug',
  description: 'description'
};

exports.Prisma.BlogPostScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  title: 'title',
  slug: 'slug',
  excerpt: 'excerpt',
  image: 'image',
  imageAlt: 'imageAlt',
  content: 'content',
  status: 'status',
  publishedAt: 'publishedAt',
  featured: 'featured',
  readingTime: 'readingTime',
  views: 'views',
  canonicalUrl: 'canonicalUrl',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  previousSlugs: 'previousSlugs',
  authorId: 'authorId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserOnlineStatus = exports.$Enums.UserOnlineStatus = {
  Away: 'Away',
  Offline: 'Offline',
  Online: 'Online'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  Active: 'Active',
  Terminated: 'Terminated',
  Inactive: 'Inactive',
  Guest: 'Guest',
  Pending: 'Pending',
  PendingNotPaid: 'PendingNotPaid',
  Withdrawn: 'Withdrawn',
  Banned: 'Banned',
  Unknown: 'Unknown'
};

exports.Role = exports.$Enums.Role = {
  Admin: 'Admin',
  Guest: 'Guest',
  User: 'User'
};

exports.DayOfWeek = exports.$Enums.DayOfWeek = {
  Monday: 'Monday',
  Tuesday: 'Tuesday',
  Wednesday: 'Wednesday',
  Thursday: 'Thursday',
  Friday: 'Friday',
  Saturday: 'Saturday',
  Sunday: 'Sunday',
  Unknown: 'Unknown'
};

exports.ChapterStatus = exports.$Enums.ChapterStatus = {
  Active: 'Active',
  NowForming: 'NowForming',
  Shutdown: 'Shutdown',
  Inactive: 'Inactive',
  Inquiry: 'Inquiry',
  PhaseOne: 'PhaseOne'
};

exports.MeetingAttendance = exports.$Enums.MeetingAttendance = {
  Absent: 'Absent',
  Present: 'Present',
  Substitute: 'Substitute',
  ApprovedLOA: 'ApprovedLOA',
  Other: 'Other'
};

exports.ChapterMemberRole = exports.$Enums.ChapterMemberRole = {
  Chairperson: 'Chairperson',
  Member: 'Member',
  Mentor: 'Mentor',
  President: 'President',
  Trainer: 'Trainer',
  VicePresident: 'VicePresident'
};

exports.ReferralRating = exports.$Enums.ReferralRating = {
  Hot: 'Hot',
  Warm: 'Warm',
  Cold: 'Cold'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  PowerHourAccepted: 'PowerHourAccepted',
  PowerHourCountered: 'PowerHourCountered',
  PowerHourDeclined: 'PowerHourDeclined',
  PowerHourReceived: 'PowerHourReceived',
  ReferralReceived: 'ReferralReceived',
  SubstituteAccepted: 'SubstituteAccepted',
  SubstituteRequested: 'SubstituteRequested',
  TestimonialReceived: 'TestimonialReceived',
  ContactInfoShared: 'ContactInfoShared'
};

exports.NotificationReferenceType = exports.$Enums.NotificationReferenceType = {
  PowerHour: 'PowerHour',
  Referral: 'Referral',
  Substitute: 'Substitute',
  Testimonial: 'Testimonial',
  SharedContact: 'SharedContact'
};

exports.PowerHourStatus = exports.$Enums.PowerHourStatus = {
  Accepted: 'Accepted',
  Countered: 'Countered',
  Declined: 'Declined',
  Proposed: 'Proposed'
};

exports.BlogPostStatus = exports.$Enums.BlogPostStatus = {
  Draft: 'Draft',
  Published: 'Published',
  Archived: 'Archived'
};

exports.Prisma.ModelName = {
  User: 'User',
  Chapter: 'Chapter',
  Meeting: 'Meeting',
  MeetingPresence: 'MeetingPresence',
  Substitute: 'Substitute',
  AttendanceReminder: 'AttendanceReminder',
  AwardType: 'AwardType',
  Award: 'Award',
  ChapterMember: 'ChapterMember',
  Upload: 'Upload',
  SubstituteGroup: 'SubstituteGroup',
  Territory: 'Territory',
  Region: 'Region',
  Industry: 'Industry',
  Referral: 'Referral',
  Notification: 'Notification',
  Transaction: 'Transaction',
  Testimonial: 'Testimonial',
  PowerHour: 'PowerHour',
  BlogCategory: 'BlogCategory',
  BlogPost: 'BlogPost'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
