mutation createUserPreference($input: SecureCreateUserPreferenceInput!) {
  createUserPreference(input: $input) {
    ...UserPreferenceDetails
  }
}

mutation deleteUserPreference($userPreferenceId: String!) {
  deleteUserPreference(userPreferenceId: $userPreferenceId) {
    id
  }
}

mutation updateUserPreference($userPreferenceId: String!, $input: SecureUpdateUserPreferenceInput!) {
  updateUserPreference(userPreferenceId: $userPreferenceId, input: $input) {
    ...UserPreferenceDetails
  }
}
