query __AdminPasswordHistory($passwordHistoryId: String!) {
  passwordHistory(passwordHistoryId: $passwordHistoryId) {
    ...__AdminPasswordHistoryDetails
  }
}

query __AdminPasswordHistories($input: ListPasswordHistoryInput) {
  passwordHistories(input: $input) {
    ...__AdminPasswordHistoryList
  }
  counters: passwordHistoriesCount(input: $input) {
    ...CorePagingDetails
  }
}

query __AdminPasswordHistoryPagination($input: ListPasswordHistoryInput) {
  counters: passwordHistoriesCount(input: $input) {
    ...CorePagingDetails
  }
}
