mutation AdminCreateUserPreference($input: CreateUserPreferenceInput!) {
  createUserPreference(input: $input) {
    ...AdminUserPreferenceDetails
  }
}

mutation AdminDeleteUserPreference($userPreferenceId: String!) {
  deleteUserPreference(userPreferenceId: $userPreferenceId) {
    id
  }
}

mutation AdminUpdateUserPreference($userPreferenceId: String!, $input: UpdateUserPreferenceInput!) {
  updateUserPreference(userPreferenceId: $userPreferenceId, input: $input) {
    ...AdminUserPreferenceDetails
  }
}
